# Generated by Django 5.2 on 2025-04-15 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movierating', '0003_movie_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='trailer_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
